import permutations from "../../test-data/move-facelet-permutations.json";
import { SOLVED_FACELETS } from "../src/cube/cube";
import { faceletsAtProgress } from "../src/guidance/guidance";
import { FACE_QUADS, arrowGeometry, faceletPolygons } from "../src/guidance/projection";
import type { CubeMove } from "../src/types";

const NOTATIONS = ["U", "U'", "U2", "R", "R'", "R2", "F", "F'", "F2"] as const;
function move(notation: typeof NOTATIONS[number]): CubeMove {
  const face = notation[0] as "U" | "R" | "F";
  const quarterTurns = notation.endsWith("2") ? 2 : notation.endsWith("'") ? -1 : 1;
  return { notation, face, quarterTurns, clockwise: quarterTurns > 0, description: notation, overlay: { visibleFace: face, surface: face.toLowerCase(), direction: "" }, resultingFacelets: SOLVED_FACELETS };
}

describe("camera guide projection", () => {
  it("keeps direct-view facelet indexing for each visible face", () => {
    for (const face of ["U", "F", "R"] as const) {
      const cells = faceletPolygons(face);
      expect(cells).toHaveLength(4);
      expect(cells.every((cell) => cell.length === 4)).toBe(true);
      const quad = FACE_QUADS[face];
      expect(cells[0][0].x).toBeCloseTo(quad[0].x, -1);
      expect(cells[3][2].x).toBeCloseTo(quad[2].x, -1);
    }
  });

  it("defines explicit direction and half-turn geometry for all nine moves", () => {
    for (const notation of NOTATIONS) {
      const geometry = arrowGeometry(move(notation));
      expect(geometry.path).toMatch(/^M/);
      expect(geometry.path).toContain(" C");
      expect(geometry.path).not.toContain(" L");
      expect(geometry.sweepSign).toBe(notation.endsWith("'") ? -1 : 1);
      expect(geometry.halfTurn).toBe(notation.endsWith("2"));
    }
  });

  it.each(["U", "R", "F"] as const)("reverses the %s path and its end arrowhead for the prime move", (face) => {
    const clockwise = arrowGeometry(move(face));
    const counterclockwise = arrowGeometry(move(`${face}'`));
    expect(counterclockwise.start).toEqual(clockwise.end);
    expect(counterclockwise.end).toEqual(clockwise.start);
    expect(counterclockwise.sweepSign).toBe(-clockwise.sweepSign);
  });

  it("consumes a complete unique-label fixture generated by the backend", () => {
    expect(Object.keys(permutations)).toEqual(NOTATIONS);
    for (const notation of NOTATIONS) {
      const labels = Object.values(permutations[notation]).flat();
      expect(new Set(labels).size).toBe(24);
      expect(labels.sort()).toEqual(Array.from({ length: 24 }, (_, index) => `${["U", "R", "F", "D", "L", "B"][Math.floor(index / 4)]}${index % 4}`).sort());
    }
  });

  it("uses returned move states as progress authority", () => {
    const first: CubeMove = { ...move("R"), resultingFacelets: { ...SOLVED_FACELETS, U: ["red", "red", "red", "red"] } };
    expect(faceletsAtProgress([first], SOLVED_FACELETS, 0)).toBe(SOLVED_FACELETS);
    expect(faceletsAtProgress([first], SOLVED_FACELETS, 1)).toBe(first.resultingFacelets);
  });
});
